document.write("");
document.write("<div class = \"container-fluid\">");
document.write("	");
document.write("	");
document.write("		<nav class = \"navbar navbar-expand-lg navbar-dark bg-dark\">");
document.write("		");
document.write("			<a class = \"navbar-brand\" href = \"index.html\">");
document.write("				<img src=\"svarog-logo.png\" class = \"nav-logo\">");
document.write("			<\/a>");
document.write("		");
document.write("			<div class = \"container\">");
document.write("				<div class = \"navbar-header\">");
document.write("				");
document.write("					<button type = \"button\" class = \"navbar-toggle\" data-toggle = \"collapse\" data-target = \"#myNavbar\">");
document.write("					<span class = \"icon-bar\"><\/span>");
document.write("					<span class = \"icon-bar\"><\/span>");
document.write("					<span class = \"icon-bar\"><\/span>");
document.write("					");
document.write("					<\/button>");
document.write("					");
document.write("				<\/div>");
document.write("				");
document.write("				<div class = \"collapse navbar-collapse\" id = \"myNavbar\">");
document.write("					<ul class = \"nav navbar-nav\">");
document.write("						<li id = \"li\"><a href=\"index.html\">HOME<\/a><\/li>");
document.write("						<li id = \"li\"><a href=\"about-us.html\">ABOUT US<\/a><\/li>");
document.write("						<li id = \"li\" class = \"dropdown\">");
document.write("							<a class = \"nav-link dropdown-toggle active\" href=\"index.html\" id = \"ourGamesDropdownLink\" data-toggle = \"dropdown\">OUR GAMES<\/a>");
document.write("							<div class = \"dropdown-menu\" aria-labelledby=\"ourGamesDropdownLink\">");
document.write("								 <p class=\"dropdown-item\">");
document.write("									 <a href=\"feminazi.html\">");
document.write("										<button class = \"navbar-game-button\"><img src = \"femi\feminazi-image.png\" class = \"navbar-icon\">Feminazi: The Triggering<\/button>");
document.write("									 <\/a>");
document.write("								 <\/p>");
document.write("								  <p class=\"dropdown-item\">");
document.write("									 <a href=\"#\">");
document.write("										<button class = \"navbar-game-button\"><img src = \"pcm\pcm-icon.png\" class = \"navbar-icon\">Prison Chainball Massacre<\//button>");
document.write("									 <\/a>");
document.write("								 <\/p>");
document.write("								  <p class=\"dropdown-item\">");
document.write("									 <a href=\"#\">");
document.write("										<button class = \"navbar-game-button\"><img src = \"femi-icon.png\" class = \"navbar-icon\">Freebie<\/button>");
document.write("									 <\/a>");
document.write("								 <\/p>");
document.write("								  <p class=\"dropdown-item\">");
document.write("									 <a href=\"#\">");
document.write("										<button class = \"navbar-game-button\"><img src = \"femi-icon.png\" class = \"navbar-icon\">Germ Wars<\/button>");
document.write("									 <\/a>");
document.write("								 <\/p>");
document.write("							<\/div>");
document.write("						<\/li>");
document.write("						<li id = \"li\"><a href=\"contact.html\">CONTACT<\/a><\/li>");
document.write("						<li id = \"li\"><a href=\"index.html\">PRESSKIT<\/a><\/li>");
document.write("						<li id = \"li\" class = \"dropdown\">");
document.write("							<a class = \"nav-link dropdown-toggle\" href=\"index.html\" id = \"ourGamesDropdownLink\" data-toggle = \"dropdown\">FUN STUFF<\/a>");
document.write("							<div class = \"dropdown-menu\" aria-labelledby=\"ourGamesDropdownLink\"  style = \"font-size: 14pt; line-height: 60px;\">");
document.write("								 <p class=\"dropdown-item\">");
document.write("									 <a href=\"insult-generator.html\">");
document.write("										<button class = \"navbar-game-button\" style = \"padding-left: 10px;\">SJW Insult Generator<\/button>");
document.write("									 <\/a>");
document.write("								 <\/p>");
document.write("								 ");
document.write("								 ");
document.write("							<\/div>");
document.write("						<\/li>");
document.write("					<\/ul>");
document.write("					");
document.write("					<a href=\"https:\/\/discordapp.com\/invite\/7YrZkEZ\" class=\"fa fa-discord pull-right\" target = \"_blank\"><\/a>");
document.write("					<a href=\"https:\/\/www.instagram.com\/svarogstudios\" class=\"fa fa-instagram pull-right\" target = \"_blank\"><\/a>");
document.write("					<a href=\"https:\/\/twitter.com\/SvarogStudios\" class=\"fa fa-twitter pull-right\" target = \"_blank\"><\/a>");
document.write("					<a href=\"https:\/\/www.facebook.com\/svarogstudios\" class=\"fa fa-facebook pull-right\" target = \"_blank\"><\/a>");
document.write("					");
document.write("					");
document.write("				<\/div>");
document.write("				");
document.write("			<\/div>");
document.write("			");
document.write("			");
document.write("			");
document.write("			");
document.write("		<\/nav>");
document.write("");
document.write("");
document.write("	");
document.write("	");
document.write("<\/div>");
